### ISSUE TITLE
功能请求：抽卡时是否可以对三星角色镀彩？

### ISSUE THREAD

**Issue by feilongproject** [staytomorrow/ba_calendar_e#1]
在进行抽卡时，是否可以对三星角色进行镀彩？另外可不可以加入new的标志？

**Comment by staytomorrow** [comment]
镀彩这个，等我再磨练磨练技术就应该能加，new的话由于现阶段没有统计抽到的角色所以暂时没有这个功能，以后可能会随着抽卡数据功能的更新而加入

**Comment by staytomorrow** [comment]
新版本已经解决
